/*
 * Copyright (c) 2025 Original Author(s), PhonePe India Pvt. Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.phonepe.sentinelai.core.model;

import org.apache.commons.lang3.NotImplementedException;

import com.phonepe.sentinelai.core.agent.AgentSetup;
import com.phonepe.sentinelai.core.agent.ModelOutputDefinition;
import com.phonepe.sentinelai.core.agent.ToolRunner;
import com.phonepe.sentinelai.core.agentmessages.AgentMessage;
import com.phonepe.sentinelai.core.earlytermination.EarlyTerminationStrategy;
import com.phonepe.sentinelai.core.hooks.AgentMessagesPreProcessor;
import com.phonepe.sentinelai.core.tools.ExecutableTool;

import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.function.Consumer;

/**
 * Abstract representation for a LLM model
 */
public interface Model {

    static int TOKEN_COUNT_UNKNOWN = -1;


    /**
     * Process messages and generate structured output. Supports both structured and tool based outputs.
     * Response will consist of a JsonNode in the form of a Map where the keys are the
     * output names and the values are the generated outputs.
     *
     * @param context                  The context of the model run, which includes metadata about the agent and the
     *                                 request.
     * @param outputDefinitions        The definitions of the outputs that the model should generate.
     * @param oldMessages              The previous messages in the conversation, which can be used to provide context
     *                                 for the model.
     * @param tools                    A map of tool names to executable tools that can be used by the model to generate
     *                                 outputs.
     * @param toolRunner               The tool runner that will execute the tools when needed.
     * @param earlyTerminationStrategy A strategy to terminate the model run earlier than expected. *
     * @return A CompletableFuture that will complete with the generated Model
     */
    CompletableFuture<ModelOutput> compute(ModelRunContext context, Collection<ModelOutputDefinition> outputDefinitions,
            List<AgentMessage> oldMessages, Map<String, ExecutableTool> tools, ToolRunner toolRunner,
            EarlyTerminationStrategy earlyTerminationStrategy,
            List<AgentMessagesPreProcessor> agentMessagesPreProcessors);

    /**
     * Estimates the token count for the given messages.
     *
     * @param messages   The list of messages to estimate the token count for.
     * @param agentSetup The setup for the agent, which includes the encoding type.
     * @return The estimated token count, or TOKEN_COUNT_UNKNOWN if not implemented.
     */
    default int estimateTokenCount(List<AgentMessage> messages, AgentSetup agentSetup) {
        return TOKEN_COUNT_UNKNOWN;
    }

    /**
     * Streams output from the model based on the provided context and messages. Supports tool calls.
     * Stream handler will be called with the output as it is generated by the model. Tool call fragments etc will
     * not be streamed out.
     *
     * @param context                    The context of the model run, which includes metadata about the agent and the
     *                                   request.
     * @param outputDefinitions          The definitions of the outputs that the model should generate.
     * @param oldMessages                The previous messages in the conversation, which can be used to provide context
     *                                   for the
     *                                   model.
     * @param tools                      List of available tools that can be used by the model to generate outputs.
     * @param toolRunner                 A runner for the tools that will execute the tools when needed.
     * @param earlyTerminationStrategy   A strategy to terminate the model run earlier than expected.
     * @param streamHandler              A consumer that will handle the streamed output from the model. It will be
     *                                   called with
     *                                   byte arrays as the output is generated.
     * @param agentMessagesPreProcessors
     * @return A CompletableFuture that will complete with the generated ModelOutput when the streaming is done.
     */
    default CompletableFuture<ModelOutput> stream(ModelRunContext context,
            Collection<ModelOutputDefinition> outputDefinitions, List<AgentMessage> oldMessages,
            Map<String, ExecutableTool> tools, ToolRunner toolRunner, EarlyTerminationStrategy earlyTerminationStrategy,
            Consumer<byte[]> streamHandler, List<AgentMessagesPreProcessor> agentMessagesPreProcessors) {
        throw new NotImplementedException();
    }

    /**
     * Streams text output from the model based on the provided context and messages. Supports tool calls.
     * Stream handler will be called with the output as it is generated by the model. Tool call fragments etc will
     * not be streamed out.
     *
     * @param context                    The context of the model run, which includes metadata about the agent and the
     *                                   request.
     * @param oldMessages                The previous messages in the conversation, which can be used to provide context
     *                                   for the
     *                                   model.
     * @param tools                      List of available tools that can be used by the model to generate outputs.
     * @param toolRunner                 A runner for the tools that will execute the tools when needed.
     * @param earlyTerminationStrategy   A strategy to terminate the model run earlier than expected.
     * @param streamHandler              A consumer that will handle the streamed output from the model. It will be
     *                                   called with
     *                                   byte arrays as the output is generated.
     * @param agentMessagesPreProcessors
     * @return A CompletableFuture that will complete with the generated ModelOutput when the streaming is done.
     */
    default CompletableFuture<ModelOutput> streamText(ModelRunContext context, List<AgentMessage> oldMessages,
            Map<String, ExecutableTool> tools, ToolRunner toolRunner, EarlyTerminationStrategy earlyTerminationStrategy,
            Consumer<byte[]> streamHandler, List<AgentMessagesPreProcessor> agentMessagesPreProcessors) {
        throw new NotImplementedException();
    }
}
