/*
 * Copyright (c) 2025 Original Author(s), PhonePe India Pvt. Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.phonepe.sentinelai.core.model;

import com.fasterxml.jackson.databind.JsonNode;
import com.phonepe.sentinelai.core.agentmessages.AgentMessage;
import com.phonepe.sentinelai.core.errors.SentinelError;
import lombok.Value;

import java.util.List;

/**
 *
 */
@Value
public class ModelOutput {
    /**
     * The output of the agent. This is typed to the required response type. In case of errors this will be null.
     */
    JsonNode data;

    /**
     * New messages generated by the agent. This will be empty in case of errors.
     */
    List<AgentMessage> newMessages;
    /**
     * All messages generated by the agent. This will include the new messages as well.
     */
    List<AgentMessage> allMessages;
    /**
     * Usage stats for the model.
     */
    ModelUsageStats usage;

    /**
     * Error in case of failure or a success object otherwise.
     */
    SentinelError error;

    public static ModelOutput success(JsonNode data, List<AgentMessage> newMessages, List<AgentMessage> allMessages, ModelUsageStats usage) {
        return new ModelOutput(data, List.copyOf(newMessages), List.copyOf(allMessages), usage, SentinelError.success());
    }

    public static ModelOutput error(List<AgentMessage> oldMessages, ModelUsageStats stats, SentinelError error) {
        return new ModelOutput(null, List.of(), List.copyOf(oldMessages), stats, error);
    }

    public static ModelOutput error(List<AgentMessage> newMessages, List<AgentMessage> allMessages, ModelUsageStats stats, SentinelError error) {
        return new ModelOutput(null, List.copyOf(newMessages), List.copyOf(allMessages), stats, error);
    }
}
