package com.phonepe.sentinelai.core.model;

import com.fasterxml.jackson.databind.JsonNode;
import com.phonepe.sentinelai.core.agentmessages.AgentMessage;
import com.phonepe.sentinelai.core.errors.SentinelError;
import lombok.Value;

import java.util.List;

/**
 *
 */
@Value
public class ModelOutput {
    /**
     * The output of the agent. This is typed to the required response type. In case of errors this will be null.
     */
    JsonNode data;

    /**
     * New messages generated by the agent. This will be empty in case of errors.
     */
    List<AgentMessage> newMessages;
    /**
     * All messages generated by the agent. This will include the new messages as well.
     */
    List<AgentMessage> allMessages;
    /**
     * Usage stats for the model.
     */
    ModelUsageStats usage;

    /**
     * Error in case of failure or a success object otherwise.
     */
    SentinelError error;

    public static ModelOutput success(JsonNode data, List<AgentMessage> newMessages, List<AgentMessage> allMessages, ModelUsageStats usage) {
        return new ModelOutput(data, newMessages, allMessages, usage, SentinelError.success());
    }

    public static ModelOutput error(List<AgentMessage> oldMessages, ModelUsageStats stats, SentinelError error) {
        return new ModelOutput(null, List.of(), oldMessages, stats, error);
    }
}
