package com.phonepe.sentinelai.core.agent;

import com.phonepe.sentinelai.core.model.ModelUsageStats;
import com.phonepe.sentinelai.core.agentmessages.AgentMessage;
import com.phonepe.sentinelai.core.errors.SentinelError;
import lombok.Value;

import java.util.List;

/**
 *
 */
@Value
public class AgentOutput<T> {
    /**
     * The output of the agent. This is typed to the required response type. In case of errors this will be null.
     */
    T data;
    /**
     * New messages generated by the agent. This will be empty in case of errors.
     */
    List<AgentMessage> newMessages;
    /**
     * All messages generated by the agent. This will include the new messages as well.
     */
    List<AgentMessage> allMessages;
    /**
     * Usage stats for the model.
     */
    ModelUsageStats usage;

    /**
     * Error in case of failure or a success object otherwise.
     */
    SentinelError error;

    public static <T> AgentOutput<T> success(T data, List<AgentMessage> newMessages, List<AgentMessage> allMessages, ModelUsageStats usage) {
        return new AgentOutput<>(data, newMessages, allMessages, usage, SentinelError.success());
    }

    public static <T> AgentOutput<T> error(List<AgentMessage> allMessages, ModelUsageStats stats, SentinelError error) {
        return new AgentOutput<>(null, List.of(), allMessages, stats, error);
    }

    public static <T> AgentOutput<T> error(List<AgentMessage> newMessages, List<AgentMessage> allMessages, ModelUsageStats stats, SentinelError error) {
        return new AgentOutput<>(null, newMessages, allMessages, stats, error);
    }
}
