package com.phonepe.sentinelai.core.agent;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.phonepe.sentinelai.core.agentmessages.AgentMessage;
import com.phonepe.sentinelai.core.tools.ToolBox;
import lombok.Value;

import java.util.List;
import java.util.Optional;
import java.util.function.Consumer;

/**
 * Can be used to extend the functionality of an agent. This can be used to add additional system prompts and facts.
 */
public interface AgentExtension<R, T, A extends Agent<R, T, A>> extends ToolBox {

    @Value
    class ExtensionPromptSchema {
        @JacksonXmlElementWrapper(localName = "tasks")
        List<SystemPrompt.Task> task;
        List<Object> hints;
    }

    /**
     * List of facts to be added to the agent system prompt.
     * For example, in a customer support agent, this can be used to add customer details as facts. Or for a RAG system
     * this can query the knowledge base and return relevant documents as facts.
     *
     * @param request Request as received by the agent
     * @param context Context for the agent run
     * @param agent   Reference to the agent
     * @return List of fact lists to be added to the agent system prompt
     */

    List<FactList> facts(R request, AgentRunContext<R> context, A agent);

    ExtensionPromptSchema additionalSystemPrompts(
            R request, AgentRunContext<R> metadata, A agent, ProcessingMode processingMode);

    Optional<ModelOutputDefinition> outputSchema(ProcessingMode processingMode);

    /**
     * Model output consumption in non-streaming mode (i.e., when {@link Agent#executeAsync(AgentInput)} is used)
     *
     * @param context  Context passed to the agent in executeAsync call
     * @param messages Messages generated during the agent run
     * @param output   Scoped output generated by the model
     * @param agent    Reference to the agent
     */
    @SuppressWarnings("unused")
    default void consumeSync(
            final AgentRunContext<R> context,
            final List<AgentMessage> messages,
            final JsonNode output,
            A agent) {
        consumeAsync(messages, output, agent);
    }

    /**
     * Model output consumption in streaming mode (i.e., when
     * {@link Agent#executeAsyncStreaming(AgentInput, Consumer)} is used)
     *
     * @param messages List of messages generated during the agent run
     * @param output   Scoped output generated by the model
     * @param agent    Reference to the agent
     */
    @SuppressWarnings("unused")
    default void consumeAsync(
            final List<AgentMessage> messages,
            final JsonNode output,
            A agent) {
        consume(output, agent);
    }

    /**
     * Simplified model output consumption method
     *
     * @param output Scoped output generated by the model
     * @param agent  Reference to the agent
     */
    default void consume(final JsonNode output, A agent) {
        // Nothing to do here by default
    }

    default List<AgentMessage> messages(AgentRunContext<R> context, A agent, R request) {
        return List.of();
    }

    /**
     * This method can be used to set-up async tasks or perform any operations once the extension is registered with
     * the agent
     *
     * @param agent Reference to the agent
     */
    default void onExtensionRegistrationCompleted(A agent) {
        //Nothing to do here for now
    }

}
