server:
  applicationConnectors:
    - type: http
      port: ${DW_PORT:-8765}
      bindHost: 127.0.0.1
  adminConnectors:
    - type: http
      port: ${DW_ADMIN_PORT:-8766}
      bindHost: 127.0.0.1
logging:
  level: WARN
  loggers:
    com.phonepe.sentinelai.examples: INFO

